name: cypherkeep
description: "Privacy-first offline security vault by SalamUniverse"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.2
  path_provider: ^2.1.3

  # Navigation
  go_router: ^14.2.0

  # Media & Files
  image_picker: ^1.1.2
  image: ^4.2.0
  share_plus: ^12.0.1
  file_picker: ^8.1.6

  # Security
  encrypt: ^5.0.3
  local_auth: ^2.2.0
  permission_handler: ^11.3.1
  crypto: ^3.0.7
  pointycastle: ^3.9.1

  # Utilities
  uuid: ^4.4.0
  intl: ^0.19.0

  # UI & Animations
  animations: ^2.0.11
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  lottie: ^3.1.2

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  riverpod_generator: ^2.4.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
    - assets/icons/
